language: node_js
node_js:
  - "node"
install:
  - "npm install"
script: npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: 1/aTc1qSUjqC9YT2KugpZTPPBfypkCVtJopeQKasDfimc
notifications:
  email: false